language: python
python:
  - "2.7"

node_js:
  - "node"

# command to install dependencies
install:
  - pip install -r devsite/requirements/base.txt
  - pip install pytest-cov flake8 tox
  - cd frontend && npm install && cd ..

# command to run tests
script:
  - cd frontend && npm run-script build && cd ..
  - flake8 figures
  - py.test --cov=./
  - bash <(curl -s https://codecov.io/bash)
  - tox

env:
  - TOXENV=py27-openedx_ginkgo
